Merge Actions into single workflow

diff --git a/.github/workflows/build-test-deploy.yml b/.github/workflows/build-test-deploy.yml
--- a/.github/workflows/build-test-deploy.yml
+++ b/.github/workflows/build-test-deploy.yml
@@ -1,14 +1,13 @@
-## Workflow based on the output of:
-## > biocthis::use_bioc_github_action()
+## Workflow partially based on the output of: biocthis::use_bioc_github_action()
 
 on:
   push:
   pull_request:
 
-name: R-CMD-check-bioc
+name: build-test-deploy
 
 ## These environment variables control whether to run GitHub Actions (GHA) code
-## later on that is specific to testthat, covr, and pkgdown.
+## later on that is specific to testthat, and pkgdown.
 ##
 ## If you need to clear the cache of packages, update the number inside
 ## cache-version as discussed at https://github.com/r-lib/actions/issues/86.
@@ -22,7 +21,7 @@ env:
   cache-version: 'cache-v1'
 
 jobs:
-  build-check:
+  build-test:
     runs-on: ${{ matrix.config.os }}
     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
     container: ${{ matrix.config.cont }}
@@ -251,12 +250,62 @@ jobs:
           name: ${{ runner.os }}-biocversion-RELEASE_3_19-r-4.4-results
           path: check
 
+  # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+  # Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+  test-coverage:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          use-public-rspm: true
+
+      - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: any::covr, any::xml2
+          needs: coverage
+
+      - name: Test coverage
+        run: |
+          cov <- covr::package_coverage(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          covr::to_cobertura(cov)
+        shell: Rscript {0}
+
+      - uses: codecov/codecov-action@v4
+        with:
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
+          file: ./cobertura.xml
+          plugin: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
 
   ## Code adapted from
   ## https://github.com/waldronlab/cBioPortalData/blob/e0440a4445f0cc731e426363a76faa22ee5e0f9d/.github/workflows/devel_check_dock.yml#L65-L92
   docker-build-and-push:
     runs-on: ubuntu-latest
-    needs: build-check
+    needs: build-test
     steps:
       - name: Checkout Repository
         if: "!contains(github.event.head_commit.message, '/nodocker') && env.run_docker == 'true' && github.ref == 'refs/heads/devel'"
